const $=id=>document.getElementById(id);
const DB={keys:[],data:{},stats:{sheets:0,rows:0,used:0,chords:0}};
let CURRENT=[],activeSound=0,audioCtx=null,currentView='cards',zoom=1,pan={x:0,y:0},drag=null,playingIndex=-1;
const noteToSemi={C:0,'B#':0,'C#':1,Db:1,D:2,'D#':3,Eb:3,E:4,Fb:4,F:5,'E#':5,'F#':6,Gb:6,G:7,'G#':8,Ab:8,A:9,'A#':10,Bb:10,B:11,Cb:11};
const CANON=['C','C#','D','Eb','E','F','F#','G','Ab','A','Bb','B'];
const romanRe=/^[b♭]?(?:I|II|III|IV|V|VI|VII)°?$/i;
const qualities={maj7:[0,4,7,11],min7:[0,3,7,10],dom7:[0,4,7,10],dim7:[0,3,6,9],min7b5:[0,3,6,10],maj9:[0,4,7,11,14],min9:[0,3,7,10,14],dom9:[0,4,7,10,14],six:[0,4,7,9],min6:[0,3,7,9],sus:[0,5,7,10],add9:[0,4,7,14]};
const sounds=[
{name:'Soft Piano',type:'triangle',attack:.012,release:.9,filter:2400,detune:0,chorus:.003},{name:'Bright Piano',type:'triangle',attack:.005,release:.65,filter:4200,detune:2,chorus:.001},{name:'Toy Keys',type:'square',attack:.004,release:.55,filter:1800,detune:7,chorus:.002},{name:'Music Box',type:'triangle',attack:.002,release:.65,filter:5000,detune:0,chorus:.001},{name:'Glass Organ',type:'sine',attack:.02,release:1.0,filter:3200,detune:12,chorus:.004},{name:'Warm Organ',type:'sine',attack:.03,release:.75,filter:1600,detune:-4,chorus:.008},{name:'Warm Pad',type:'sawtooth',attack:.09,release:1.45,filter:900,detune:-5,chorus:.007},{name:'Dream Pad',type:'sine',attack:.11,release:1.8,filter:1200,detune:16,chorus:.01},{name:'Retro Poly',type:'sawtooth',attack:.01,release:.7,filter:1500,detune:9,chorus:.005},{name:'Square Poly',type:'square',attack:.008,release:.62,filter:1300,detune:-9,chorus:.004},{name:'Muted Pluck',type:'square',attack:.001,release:.38,filter:1100,detune:-8,chorus:.001},{name:'Rubber Pluck',type:'triangle',attack:.001,release:.32,filter:850,detune:20,chorus:.001},{name:'Sample-ish Keys',type:'sine',attack:.035,release:1.15,filter:1350,detune:18,chorus:.008},{name:'Old Tape Keys',type:'triangle',attack:.025,release:.95,filter:1150,detune:-18,chorus:.011},{name:'Ghost Choir',type:'sine',attack:.16,release:1.9,filter:950,detune:7,chorus:.012},{name:'Tiny Casio',type:'square',attack:.003,release:.5,filter:2100,detune:14,chorus:.002}
];
function clean(s){return (s||'').replace(/\s+/g,' ').trim()}
function esc(s){return clean(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function displaySubLabel(s){return clean(s).replace(/^All\s+/i,'')}
function parseLabel(label){const parts=clean(label).replace(/♯/g,'#').replace(/♭/g,'b').split(/\s+/).filter(Boolean);if(!parts.length)return['C','maj7'];const qTok=parts.find(p=>/^(maj9|m9|min9|dom9|maj7|dom7|min7b5|min7|dim7|m7b5|ø7|7|6|m6|sus|sus4|add9)$/i.test(p));let q=null;if(qTok){const x=qTok.toLowerCase();q=x==='m7b5'||x==='ø7'?'min7b5':x==='7'?'dom7':x==='6'?'six':x==='m6'?'min6':x==='m9'?'min9':x==='sus4'?'sus':x;}let rootTokens=parts;if(romanRe.test(parts.at(-1)||''))rootTokens=parts.slice(0,-1);let root=rootTokens.filter(t=>!t.match(/^(maj9|m9|min9|dom9|maj7|dom7|min7b5|min7|dim7|m7b5|ø7|7|6|m6|sus|sus4|add9)$/i)).join('');root=root.match(/[A-G](?:#|b)?/)?.[0]||'C';if(!q){q=rootTokens.join('').endsWith('m')?'min7':'maj7';root=root.replace(/m$/,'')}return[root,q]}
function chordSemis(label){const[r,q]=parseLabel(label);const base=noteToSemi[r]??0;return(qualities[q]||qualities.maj7).map(i=>base+i)}
function noteName(n){return CANON[((n%12)+12)%12]}
function voiceChord(label){const pcs=chordSemis(label).map(n=>((n%12)+12)%12);const[root]=parseLabel(label);const rootPc=noteToSemi[root]??0;const out=[];pcs.forEach((pc,i)=>{let n=48+pc;while(n<52)n+=12;while(n>76)n-=12;if(i&&out.length&&n<=out[out.length-1].midi)n+=12;out.push({pc,midi:n,root:pc===rootPc})});if(out[0]?.pc!==rootPc)out.unshift({pc:rootPc,midi:36+rootPc,root:true});while(out[0].midi>45)out[0].midi-=12;return out.slice(0,5).sort((a,b)=>a.midi-b.midi)}
function ingestXLSX(wb){const data={};let rows=0,used=0,chords=0;(wb.SheetNames||[]).forEach(sheet=>{const ws=wb.Sheets[sheet];if(!ws)return;const arr=XLSX.utils.sheet_to_json(ws,{header:1,raw:true,blankrows:false});if(!arr||arr.length<2)return;const key=clean(sheet);let lastBase='',lastSub='';rows+=arr.length-1;for(let r=1;r<arr.length;r++){const row=arr[r]||[];const baseCell=clean(row[1]);if(baseCell)lastBase=baseCell;const subCell=clean(row[2]);if(subCell)lastSub=subCell;const family=clean(row[3]);if(!lastBase||!lastSub)continue;const degrees=[];for(let c=4;c<600;c++){const v=clean(row[c]);if(v)degrees.push(v)}if(!degrees.length)continue;used++;chords+=degrees.length;(((data[key]||={})[lastBase]||={})[lastSub]||=[]).push({family,degrees});}});DB.keys=Object.keys(data).sort();DB.data=data;DB.stats={sheets:(wb.SheetNames||[]).length,rows,used,chords}}
async function loadBuffer(ab){const wb=XLSX.read(ab,{type:'array'});ingestXLSX(wb);populateSelectors();loaderPanel.classList.add('hidden');dataStatus.textContent=`${DB.keys.length} keys · ${DB.stats.chords} chords from data`;generate()}
async function loadURL(url){const res=await fetch(url);if(!res.ok)throw new Error(`${res.status} ${res.statusText}`);await loadBuffer(await res.arrayBuffer())}
async function tryAutoload(){const q=new URLSearchParams(location.search).get('xlsx');for(const u of [q,'../data.xlsx','../ChordWeb.xlsx','../chordweb.xlsx'].filter(Boolean)){try{await loadURL(u);dataUrl.value=u;return true}catch(e){}}return false}
function populateSelectors(){soundSelect.innerHTML=sounds.map((s,i)=>`<option value="${i}">${esc(s.name)}</option>`).join('');rootSel.innerHTML='<option>Any Key</option>'+DB.keys.map(k=>`<option>${esc(k)}</option>`).join('');refreshBaseSub();refreshStartChoices()}
function refreshBaseSub(){const root=rootSel.value;let bases=[];(root==='Any Key'?DB.keys:[root]).forEach(k=>bases.push(...Object.keys(DB.data[k]||{})));bases=[...new Set(bases)].sort();baseSel.innerHTML='<option>Any Base</option>'+bases.map(b=>`<option>${esc(b)}</option>`).join('');refreshSubs()}
function refreshSubs(){const root=rootSel.value,base=baseSel.value;let subs=[];(root==='Any Key'?DB.keys:[root]).forEach(k=>{(base==='Any Base'?Object.keys(DB.data[k]||{}):[base]).forEach(b=>subs.push(...Object.keys((DB.data[k]||{})[b]||{})))});subs=[...new Set(subs)].sort((a,b)=>displaySubLabel(a).localeCompare(displaySubLabel(b)));subSel.innerHTML='<option>Any Sub</option>'+subs.map(s=>`<option value="${esc(s)}">${esc(displaySubLabel(s))}</option>`).join('');refreshStartChoices()}
function allPool(){const root=rootSel.value,base=baseSel.value,sub=subSel.value;const out=[];(root==='Any Key'?DB.keys:[root]).forEach(k=>{(base==='Any Base'?Object.keys(DB.data[k]||{}):[base]).forEach(b=>{(sub==='Any Sub'?Object.keys((DB.data[k]||{})[b]||{}):[sub]).forEach(s=>{((DB.data[k]||{})[b]||{})[s]?.forEach(row=>row.degrees.forEach(label=>out.push({label:clean(label),key:k,base:b,sub:s,family:row.family})))});});});return out}
function refreshStartChoices(){const seen=new Set();const opts=allPool().filter(o=>{if(seen.has(o.label))return false;seen.add(o.label);return true}).slice(0,650);startSel.innerHTML='<option value="">Optional</option>'+opts.map(o=>`<option value="${esc(o.label)}">${esc(o.label)}</option>`).join('')}
function scoreItem(o){const scary=+spicy.value/100;const hay=`${o.label} ${o.base} ${o.sub} ${o.family}`.toLowerCase();let spice=0;if(/phrygian|locrian|altered|tritone|dim|ø|min7b5|chromatic|bii|♭ii|bv|♭v|bvi|♭vi/.test(hay))spice+=4;if(/dom7|dim7|min9|maj9|sus|lydian|dorian/.test(hay))spice+=2;if(/ionian|major|maj7|min7/.test(hay))spice-=1;return 1+Math.max(.1,(scary*spice)+((1-scary)*(3-Math.max(0,spice))))}
function pickWeighted(arr){const scored=arr.map(o=>({...o,score:scoreItem(o)}));const total=scored.reduce((a,o)=>a+o.score,0);let r=Math.random()*total;for(const o of scored){r-=o.score;if(r<=0)return o}return scored.at(-1)}
function generate(){const p=allPool();if(!p.length){cards.innerHTML='<article class="card"><div class="chordName">No chords</div><p class="meta">Try a wider Root/Base/Sub choice or load data.</p></article>';webZoom.innerHTML='';return}const target=Math.max(1,Math.min(48,+count.value||8));CURRENT=[];playingIndex=-1;const seen=new Set();const start=startSel.value;if(start){const s=p.find(o=>o.label===start);if(s){CURRENT.push(s);seen.add(s.label)}}let guard=0;while(CURRENT.length<target&&guard++<1200){const x=pickWeighted(p);const key=noRepeat.checked?x.label:x.label+'|'+Math.random();if(!seen.has(key)){seen.add(key);CURRENT.push(x)}}renderCards();renderMap()}
function renderCards(){cards.innerHTML=CURRENT.map((c,i)=>`<article class="card ${i===playingIndex?'playing':''}" id="card-${i}"><div class="cardTop"><div><div class="chordName">${esc(c.label)}</div><div class="meta">${esc(c.key)} · ${esc(c.base)}<br>${esc(displaySubLabel(c.sub))}${c.family?' · '+esc(c.family):''}</div></div><button class="playBtn" data-play="${i}">▶</button></div>${keyboardSVG(voiceChord(c.label))}</article>`).join('');cards.querySelectorAll('[data-play]').forEach(b=>b.addEventListener('click',()=>playIndex(+b.dataset.play,true)))}
function keyboardSVG(v){const start=48,white=[0,2,4,5,7,9,11],black=[1,3,6,8,10],W=28,H=108;let whiteIndex={},x=0,html=`<svg class="keyboard" viewBox="0 0 ${W*15} ${H}" role="img" aria-label="Piano notes">`;for(let n=start;n<=72;n++){const pc=n%12;if(white.includes(pc)){whiteIndex[n]=x;html+=`<rect class="whiteKey" x="${x*W}" y="0" width="${W}" height="${H}" rx="3"/>`;x++}}for(let n=start;n<=72;n++){const pc=n%12;if(black.includes(pc)){let prev=n-1;while(!whiteIndex.hasOwnProperty(prev))prev--;html+=`<rect class="blackKey" x="${whiteIndex[prev]*W+W*.64}" y="0" width="${W*.68}" height="${H*.58}" rx="3"/>`}}v.forEach(n=>{let midi=n.midi;while(midi<start)midi+=12;while(midi>72)midi-=12;const pc=midi%12;let cx,cy;if(white.includes(pc)){cx=whiteIndex[midi]*W+W/2;cy=H-28}else{let prev=midi-1;while(!whiteIndex.hasOwnProperty(prev))prev--;cx=whiteIndex[prev]*W+W*.98;cy=38}html+=`<circle class="noteMark ${n.root?'root':''}" cx="${cx}" cy="${cy}" r="13"/><text class="noteText" x="${cx}" y="${cy}">${noteName(n.midi)}</text>`});return html+'</svg>'}
function ensureAudio(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}
function freq(m){return 440*Math.pow(2,(m-69)/12)}
function playChord(chord,when=0,dur=.78){const ctx=ensureAudio(),s=sounds[activeSound],master=ctx.createGain(),filter=ctx.createBiquadFilter();master.gain.value=+volume.value/100*.2;filter.type='lowpass';filter.frequency.value=s.filter;filter.connect(master).connect(ctx.destination);voiceChord(chord.label).forEach((n,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type=s.type;o.detune.value=s.detune+(i-2)*2;o.frequency.value=freq(n.midi);g.gain.setValueAtTime(0,ctx.currentTime+when);g.gain.linearRampToValueAtTime(1/(i?1.8:2.5),ctx.currentTime+when+s.attack);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+when+dur+s.release);o.connect(g).connect(filter);o.start(ctx.currentTime+when);o.stop(ctx.currentTime+when+dur+s.release+.05);if(s.chorus){const o2=ctx.createOscillator(),g2=ctx.createGain();o2.type=s.type;o2.detune.value=s.detune+10;o2.frequency.value=freq(n.midi);g2.gain.value=s.chorus;o2.connect(g2).connect(filter);o2.start(ctx.currentTime+when);o2.stop(ctx.currentTime+when+dur+s.release+.05)}})}
function setPlaying(i){playingIndex=i;document.querySelectorAll('.card').forEach((c,idx)=>c.classList.toggle('playing',idx===i));document.querySelectorAll('.node').forEach((n,idx)=>n.classList.toggle('playing',idx===i))}
function playIndex(i,scroll=false){if(!CURRENT[i])return;setPlaying(i);playChord(CURRENT[i]);if(scroll&&currentView==='cards')$('card-'+i)?.scrollIntoView({behavior:'smooth',block:'center'})}
async function playAll(){ensureAudio();for(let i=0;i<CURRENT.length;i++){playIndex(i,currentView==='cards');await new Promise(r=>setTimeout(r,+playSpeed.value||850))}}
function relation(a,b){const[ar,aq]=parseLabel(a.label),[br,bq]=parseLabel(b.label);const A=noteToSemi[ar]??0,B=noteToSemi[br]??0,d=(B-A+12)%12;if(d===5)return aq==='min7'&&bq==='dom7'?'ii→V':'4th';if(d===7)return '5th';if(d===6)return 'tritone';if([3,4,8,9].includes(d))return 'mediant';if(d===1||d===11)return '½-step';if(A===B)return 'same root';return `${d}↑`}
function mapPoints(){const W=1200,H=900,cx=W/2,cy=H/2,n=CURRENT.length||1;if(currentView==='const'){const rings=[155,255,355,455];return CURRENT.map((c,i)=>{const r=rings[i%rings.length],lap=Math.floor(i/rings.length),a=(i/n)*Math.PI*2-Math.PI/2+lap*.18;return{...c,x:cx+Math.cos(a)*r,y:cy+Math.sin(a)*r}})}const cols=Math.max(2,Math.ceil(Math.sqrt(n)));const gapX=320,gapY=170,startX=cx-(cols-1)*gapX/2;return CURRENT.map((c,i)=>({ ...c,x:startX+(i%cols)*gapX,y:110+Math.floor(i/cols)*gapY }))}
function renderMap(){if(!CURRENT.length){webZoom.innerHTML='';return}const pts=mapPoints();const hubMap=new Map();pts.forEach(p=>{const k=currentView==='const'?p.base:p.sub;if(!hubMap.has(k))hubMap.set(k,[]);hubMap.get(k).push(p)});let html=`<g transform="translate(${pan.x},${pan.y}) scale(${zoom})">`;if(currentView==='const')html+='<circle class="ring" cx="600" cy="450" r="155"/><circle class="ring" cx="600" cy="450" r="255"/><circle class="ring" cx="600" cy="450" r="355"/><circle class="ring" cx="600" cy="450" r="455"/><text class="ringLabel" x="600" y="42">Constellation follows the exact generated card order</text>';for(const [name,group] of hubMap.entries()){const hx=group.reduce((a,p)=>a+p.x,0)/group.length,hy=group.reduce((a,p)=>a+p.y,0)/group.length;html+=`<circle class="hub" cx="${hx}" cy="${hy}" r="${Math.min(70,28+group.length*4)}"/><text class="nodeMeta" x="${hx}" y="${hy-18}">${esc(displaySubLabel(name)).slice(0,28)}</text>`;group.forEach(p=>html+=`<line class="hubEdge" x1="${hx}" y1="${hy}" x2="${p.x}" y2="${p.y}"/>`)}for(let i=0;i<pts.length-1;i++){const a=pts[i],b=pts[i+1],mx=(a.x+b.x)/2,my=(a.y+b.y)/2;html+=`<line class="edge ${relation(a,b)==='½-step'||relation(a,b)==='tritone'?'strong':''}" x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}"/><text class="edgeLabel" x="${mx}" y="${my-6}">${relation(a,b)}</text>`}pts.forEach((p,i)=>{const w=Math.max(118,Math.min(185,p.label.length*8+36));html+=`<g class="mapNode" data-i="${i}"><rect class="mapCard" x="${p.x-w/2}" y="${p.y-35}" width="${w}" height="70" rx="16"/><circle class="node ${i===playingIndex?'playing':''}" cx="${p.x}" cy="${p.y-8}" r="18"/><text class="seqText" x="${p.x}" y="${p.y-8}">${i+1}</text><text class="nodeText" x="${p.x}" y="${p.y+25}">${esc(p.label)}</text><text class="nodeMeta" x="${p.x}" y="${p.y+43}">${esc(p.key)} · ${esc(displaySubLabel(p.sub)).slice(0,22)}</text></g>`});webZoom.innerHTML=html+'</g>';webZoom.querySelectorAll('.mapNode').forEach(n=>n.addEventListener('click',e=>{e.stopPropagation();playIndex(+n.dataset.i,false)}))}
function setView(v){currentView=v;cards.classList.toggle('hidden',v!=='cards');mapPanel.classList.toggle('hidden',v==='cards');cardsViewBtn.classList.toggle('active',v==='cards');webViewBtn.classList.toggle('active',v==='web');constViewBtn.classList.toggle('active',v==='const');renderMap();if(v!=='cards')mapPanel.scrollIntoView({behavior:'smooth',block:'start'})}
function setSound(i){activeSound=(+i+sounds.length)%sounds.length;soundSelect.value=activeSound}
function randSelect(sel){if(sel.options.length>1){sel.selectedIndex=1+Math.floor(Math.random()*(sel.options.length-1));sel.dispatchEvent(new Event('change'))}}
function randomAll(){randSelect(rootSel);randSelect(baseSel);randSelect(subSel);startSel.value='';generate()}
function resetAll(){rootSel.selectedIndex=0;refreshBaseSub();subSel.selectedIndex=0;startSel.value='';count.value=8;spicy.value=0;noRepeat.checked=true;playSpeed.value=850;speedReadout.textContent='850ms';zoom=1;pan={x:0,y:0};generate()}
function copyText(){navigator.clipboard?.writeText(CURRENT.map((c,i)=>`${i+1}. ${c.label} — ${c.key} / ${c.base} / ${displaySubLabel(c.sub)}`).join('\n'));copyBtn.textContent='Copied';setTimeout(()=>copyBtn.textContent='Copy',900)}
fileInput.addEventListener('change',async e=>{const f=e.target.files[0];if(f)await loadBuffer(await f.arrayBuffer())});loadUrlBtn.addEventListener('click',async()=>{try{await loadURL(dataUrl.value)}catch(e){dataStatus.textContent='Load failed: '+e.message}});rootSel.addEventListener('change',()=>{refreshBaseSub();generate()});baseSel.addEventListener('change',()=>{refreshSubs();generate()});subSel.addEventListener('change',()=>{refreshStartChoices();generate()});startSel.addEventListener('change',generate);count.addEventListener('change',generate);spicy.addEventListener('input',generate);noRepeat.addEventListener('change',generate);playSpeed.addEventListener('input',()=>speedReadout.textContent=playSpeed.value+'ms');generateBtn.addEventListener('click',generate);playAllBtn.addEventListener('click',playAll);copyBtn.addEventListener('click',copyText);rootRnd.addEventListener('click',()=>randSelect(rootSel));baseRnd.addEventListener('click',()=>randSelect(baseSel));subRnd.addEventListener('click',()=>randSelect(subSel));startRnd.addEventListener('click',()=>randSelect(startSel));randomAllBtn.addEventListener('click',randomAll);resetBtn.addEventListener('click',resetAll);soundSelect.addEventListener('change',()=>setSound(soundSelect.value));randomSoundBtn.addEventListener('click',()=>setSound(Math.floor(Math.random()*sounds.length)));cardsViewBtn.addEventListener('click',()=>setView('cards'));webViewBtn.addEventListener('click',()=>setView('web'));constViewBtn.addEventListener('click',()=>setView('const'));settingsJump.addEventListener('click',()=>controls.scrollIntoView({behavior:'smooth'}));zoomIn.addEventListener('click',()=>{zoom=Math.min(9,zoom*1.28);renderMap()});zoomOut.addEventListener('click',()=>{zoom=Math.max(.2,zoom/1.28);renderMap()});zoomReset.addEventListener('click',()=>{zoom=1;pan={x:0,y:0};renderMap()});webSvg.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.2,Math.min(9,zoom*(e.deltaY<0?1.14:.88)));renderMap()},{passive:false});webSvg.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};webSvg.setPointerCapture(e.pointerId)});webSvg.addEventListener('pointermove',e=>{if(!drag)return;pan.x=drag.px+e.clientX-drag.x;pan.y=drag.py+e.clientY-drag.y;renderMap()});webSvg.addEventListener('pointerup',()=>drag=null);soundSelect.innerHTML=sounds.map((s,i)=>`<option value="${i}">${esc(s.name)}</option>`).join('');speedReadout.textContent=playSpeed.value+'ms';setSound(0);tryAutoload();